### PR TITLE
General and vision fixes

### PR DESCRIPTION
**Pull request by Samasaur1**

### CODE REVIEW

**Comment by jrr6** [comment]
FYI, this PR doesn't compile

**Comment by Samasaur1** [comment]
Yep, saw it and am fixing

**Comment by aaplmath** [comment]
Also, why does VQR now require Drivetrain?

**Comment by Samasaur1** [comment]
Ah, the base hadn't been updating, but there we go

**Comment by jrr6** [comment]
Also, why does VQC now require Drivetrain? (I'm assuming this has something to do with `RequirementFreeRotateAngleOffsetAuton`?)

**Comment by Samasaur1** [comment]
> Also, why does VQR now require Drivetrain? (I'm assuming this has something to do with `RequirementFreeRotateAngleOffsetAuton`?)

You are correct. We started by testing using a `DriveAndShootAuton`, seen here:
https://github.com/Roobotics-FRC/RooBot2020/blob/2d04b0ff08efe82054acf9b438c9505d3abf8eec/src/main/java/frc/team4373/robot/commands/DriveAndShootAuton.java#L1-L15
There were two behaviors that we saw. The first was when the robot was within its tolerance after backing up. In this case, the robot shot for 5 seconds and ended. The second behavior was the robot turning (using `VisionQuerierAuton`), but after it finished, the robot did not shoot. Further observation showed `DriveAndShootAuton` in the scheduler during the movement (which is normal, as it does not show subcommands), and when the turning started, `RotateAngleOffsetAuton` was added to the Scheduler. However (as far as I can tell), this interrupted the command group. So the rotate auton finished, but the command group had been interrupted and so never shot. I'm not sure if the VisionQuerierCommand continued or was interrupted when the command group was interrupted (whether it would run the rotate auton twice or just once).

The issue as I saw it was that `RotateAngleOffsetAuton` interrupts the command group. So I made a constructor that did not call `requires()` on the drivetrain (FYI, the code here has not been tested. The tested code is available at the [`working-auton-code` tag](https://github.com/Roobotics-FRC/RooBot2020/tree/working-auton-code)). However, for safety, I added a requirement to `VisionQuerierCommand` for `Drivetrain` (as it does control the drivetrain).

**Comment by Samasaur1** [comment]
`RequirementFreeRotateAngleOffsetAuton` is an extension of `RotateAngleOffsetAuton` that clears its requirements, as I reverted `RotateAngleOffsetAuton` to its prior state

**Comment by Samasaur1** [comment]
The `DriveAndShootAuton` command group now also strafes to the right after aiming (to line the shooter up with the target, instead of the camera.

**Pull request merged**
